parameters:
    database_host: mysql
    database_port: ~
    database_name: '%env(MYSQL_DATABASE)%'
    database_user: '%env(MYSQL_USER)%'
    database_password: '%env(MYSQL_PASSWORD)%'

    deeplApiKey: '%env(DEEPL_API_KEY)%'
    env(DEEPL_API_KEY): 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx:fx'
    deeplTargetLanguage: '%env(DEEPL_TARGET_LANGUAGE)%'
    env(DEEPL_TARGET_LANGUAGE): 'fr'
    deeplDomainUrl: '%env(DEEPL_DOMAIN_URL)%'
    env(DEEPL_DOMAIN_URL): 'api-free.deepl.com'

    rssSourceUrl: '%env(SOURCE_RSS_URL)%'
    env(SOURCE_RSS_URL): 'https://feedforall.com/sample.xml'

    livesquawkUrl: '%env(PROVIDER_URL)%'
    env(PROVIDER_URL): '-'
    livesquawkAuthKey: '%env(PROVIDER_AUTH_KEY)%'
    env(PROVIDER_AUTH_KEY): 'changeme'
